var GAME_LEVELS = [
  ["                                                                               ",
   "                                                                               ",
   "                                                         !!!!!!!!!!!!!!!!!!!!!!",
   "                                                     xxxxx   xxx   xxx   xxxxxx",
   "                    x  #     x                                              f  ",
   "            x   x   x     #  xx     xx    xx   xx                              ",
   "                                                                               ",
   "                                                                               ",
   "                             |                  |                              ",
   " x                     p                              f                     o x",
   " x                 xxxxxxxxxx   xxx   xxx   xxx   xxxxx                  xxxxxx",
   " x @            xxxx                |      |           ! ! ! ! ! ! ! ! ! !     ",
   " xxxxxxxxxxxxxxxx            xx    xx     xx   xx       ! ! ! ! ! ! ! ! ! !    ",
   "                                                                               ",
   "                                                                               ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "                                                                            ",
    "                                                                            ",
    "         x                                                                  ",
    "                                                                            ",
    "                  xxx            xxx                                        ",
    "                                   f                                        ",
    "                         xxx                                                ",
    "    xxxx    xxx                                                             ",
    "                                                                            ",
    "x                                                                           ",
    "x                   x #         x                                           ",
    "x                   x        #  x         xx                              #x",
    "x        |                                           xx                   #x",
    "x        x                           xx                                   #x",
    "x@  f                                   p      p                          #x",
    "xxxxx                              xxxxxxxxxxxxxxxxxxxxxxxx               #x",
    "                                                          xx              ox",
    "                                                           xxxxxxxxxxxxxxxxx",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
    ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
     "                                                                                   ",
     "                                                                                   ",
     "                                                                                   ",
     "                                                                                   ",
     "                                                                                   ",
     "                                                                                   ",
     "                                                                                   ",
     "         x            x              x  #x # x#  x#  x#  x#  x                     ",
     " x                                                           f                   <x",
     "                                                                                   ",
     "    x                                                                              ",
     "                      |                                                            ",
     "                                                                                   ",
     "         |                                                                         ",
     "                                                                                   ",
     "x@     p     p     p     p     p     f                                          o  ",
     "xxx |  x     x     x     x     x     x                       xxxx       #    xxxx  ",
     "                                                               xxxxxxxxxxxxxxx     ",
     "    x    x            x",
     "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
     "                                                                                   "],
["                                     o",
"         x     x  x  xx  x         ",
"          x x x   x  x x x         ",
"           x x    x  x  xx         ",
"@                                      ",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
